# Generated by Django 5.2.1 on 2025-08-27 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('coupons', '0005_tag_useroffer_remove_couponusage_coupon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryanalytics',
            old_name='coupon_clicks',
            new_name='offer_clicks',
        ),
        migrations.RenameField(
            model_name='storeanalytics',
            old_name='coupon_clicks',
            new_name='offer_clicks',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('click', 'Click'), ('search', 'Search'), ('filter', 'Filter'), ('save_offer', 'Save Offer'), ('copy_code', 'Copy Code'), ('view_offer', 'View Offer'), ('use_offer', 'Use Offer'), ('scroll', 'Scroll'), ('page_view', 'Page View'), ('form_submit', 'Form Submit')], max_length=50),
        ),
        migrations.CreateModel(
            name='OfferAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0)),
                ('saves', models.PositiveIntegerField(default=0)),
                ('code_copies', models.PositiveIntegerField(default=0)),
                ('uses', models.PositiveIntegerField(default=0)),
                ('last_viewed', models.DateTimeField(blank=True, null=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='coupons.coupon')),
            ],
            options={
                'verbose_name_plural': 'Offer Analytics',
            },
        ),
        migrations.DeleteModel(
            name='CouponAnalytics',
        ),
    ]
