# Generated by Django 5.2.1 on 2025-08-12 09:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CouponProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('api_url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(default='CouPradise - Save Money with Exclusive Coupons', max_length=255)),
                ('meta_description', models.TextField(default='Discover the best coupons, promo codes and deals from your favorite stores. Save money on your online shopping with CouPradise.')),
                ('meta_keywords', models.CharField(default='coupons, promo codes, deals, discounts, savings, coupon codes', max_length=255)),
                ('og_title', models.CharField(default='CouPradise - Save Money with Exclusive Coupons', max_length=255)),
                ('og_description', models.TextField(default='Discover the best coupons, promo codes and deals from your favorite stores. Save money on your online shopping with CouPradise.')),
                ('og_image', models.URLField(blank=True)),
                ('og_image_upload', models.ImageField(blank=True, null=True, upload_to='seo/og_images/')),
                ('twitter_title', models.CharField(default='CouPradise - Save Money with Exclusive Coupons', max_length=255)),
                ('twitter_description', models.TextField(default='Discover the best coupons, promo codes and deals from your favorite stores. Save money on your online shopping with CouPradise.')),
                ('twitter_image', models.URLField(blank=True)),
                ('twitter_image_upload', models.ImageField(blank=True, null=True, upload_to='seo/twitter_images/')),
                ('canonical_url', models.URLField(blank=True)),
                ('no_index', models.BooleanField(default=False)),
                ('no_follow', models.BooleanField(default=False)),
                ('hero_title', models.CharField(default='Save Money with Exclusive Coupons', max_length=255)),
                ('hero_description', models.TextField(default='Discover the best deals and discounts from your favorite stores.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage SEO',
                'verbose_name_plural': 'Homepage SEO',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('coupon_type', models.CharField(choices=[('CODE', 'Discount Code'), ('DEAL', 'Deal'), ('PRINTABLE', 'Printable Coupon'), ('FREE_SHIPPING', 'Free Shipping')], default='CODE', max_length=20)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount'), ('BOGO', 'Buy One Get One'), ('FREE', 'Free Item')], default='PERCENTAGE', max_length=20)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('minimum_purchase', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('affiliate_link', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='coupons.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_coupons', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='coupons.couponprovider')),
            ],
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='coupons.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('home', 'Homepage'), ('coupon', 'Coupon'), ('store', 'Store'), ('category', 'Category'), ('page', 'Static Page')], max_length=20)),
                ('content_id', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.URLField(blank=True)),
                ('og_image_upload', models.ImageField(blank=True, null=True, upload_to='seo/og_images/')),
                ('twitter_title', models.CharField(blank=True, max_length=255)),
                ('twitter_description', models.TextField(blank=True)),
                ('twitter_image', models.URLField(blank=True)),
                ('twitter_image_upload', models.ImageField(blank=True, null=True, upload_to='seo/twitter_images/')),
                ('canonical_url', models.URLField(blank=True)),
                ('no_index', models.BooleanField(default=False)),
                ('no_follow', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Metadata',
                'verbose_name_plural': 'SEO Metadata',
                'unique_together': {('content_type', 'content_id')},
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='seo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon', to='coupons.seo'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='coupons.seo'),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('website', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store_logos/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store', to='coupons.seo')),
            ],
        ),
        migrations.AddField(
            model_name='coupon',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='coupons.store'),
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='coupons.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'coupon')},
            },
        ),
    ]
