# Generated by Django 5.2.1 on 2025-08-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
