# Generated by Django 5.2.1 on 2025-08-06 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
