# Generated by Django 5.2.1 on 2025-08-26 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_coupon_slug'),
    ]

    operations = [
    ]
