# Generated by Django 5.2.1 on 2025-08-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_auto_20250826_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
