# Generated by Django 5.2.1 on 2025-08-27 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_alter_coupon_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User Offer',
                'verbose_name_plural': 'User Offers',
            },
        ),
        migrations.RemoveField(
            model_name='couponusage',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='couponusage',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='usercoupon',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usercoupon',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='usercoupon',
            name='user',
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='source',
            field=models.CharField(choices=[('DIRECT', 'Direct Entry'), ('AMAZON', 'Amazon'), ('AFFILIATE', 'Affiliate Network'), ('OTHER', 'Other Source')], default='DIRECT', max_length=20),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='coupons.category'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='coupons.couponprovider'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='seo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer', to='coupons.seo'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='coupons.store'),
        ),
        migrations.AlterField(
            model_name='homepageseo',
            name='hero_title',
            field=models.CharField(default='Save Money with Exclusive Offers', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepageseo',
            name='meta_description',
            field=models.TextField(default='Discover the best offers, promo codes and deals from your favorite stores. Save money on your online shopping with CouPradise.'),
        ),
        migrations.AlterField(
            model_name='homepageseo',
            name='meta_keywords',
            field=models.CharField(default='offers, promo codes, deals, discounts, savings, coupon codes', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepageseo',
            name='meta_title',
            field=models.CharField(default='CouPradise - Save Money with Exclusive Offers', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepageseo',
            name='og_description',
            field=models.TextField(default='Discover the best offers, promo codes and deals from your favorite stores. Save money on your online shopping with CouPradise.'),
        ),
        migrations.AlterField(
            model_name='homepageseo',
            name='og_title',
            field=models.CharField(default='CouPradise - Save Money with Exclusive Offers', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepageseo',
            name='twitter_description',
            field=models.TextField(default='Discover the best offers, promo codes and deals from your favorite stores. Save money on your online shopping with CouPradise.'),
        ),
        migrations.AlterField(
            model_name='homepageseo',
            name='twitter_title',
            field=models.CharField(default='CouPradise - Save Money with Exclusive Offers', max_length=255),
        ),
        migrations.AlterField(
            model_name='seo',
            name='content_type',
            field=models.CharField(choices=[('home', 'Homepage'), ('offer', 'Offer'), ('store', 'Store'), ('category', 'Category'), ('page', 'Static Page')], max_length=20),
        ),
        migrations.CreateModel(
            name='OfferUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='coupons.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offer Usage',
                'verbose_name_plural': 'Offer Usages',
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='offers', to='coupons.tag'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['slug'], name='coupons_cou_slug_69c249_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['source'], name='coupons_cou_source_57372b_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['coupon_type'], name='coupons_cou_coupon__d1f056_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_special'], name='coupons_cou_is_spec_8b3483_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_popular'], name='coupons_cou_is_popu_76e01a_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_featured'], name='coupons_cou_is_feat_e6bba0_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_verified'], name='coupons_cou_is_veri_af1b36_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['start_date'], name='coupons_cou_start_d_9e0133_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['expiry_date'], name='coupons_cou_expiry__fb3a0a_idx'),
        ),
        migrations.AddField(
            model_name='useroffer',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='coupons.coupon'),
        ),
        migrations.AddField(
            model_name='useroffer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CouponUsage',
        ),
        migrations.DeleteModel(
            name='UserCoupon',
        ),
        migrations.AlterUniqueTogether(
            name='useroffer',
            unique_together={('user', 'offer')},
        ),
    ]
