# Generated by Django 5.2.1 on 2025-08-27 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_tag_useroffer_remove_couponusage_coupon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Deal Section',
                'verbose_name_plural': 'Deal Sections',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DealHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='coupons.coupon')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='coupons.dealsection')),
            ],
            options={
                'verbose_name': 'Deal Highlight',
                'verbose_name_plural': 'Deal Highlights',
                'ordering': ['display_order'],
            },
        ),
    ]
