# Generated by Django 5.2.1 on 2025-08-06 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(default='CouponHub - Save Money with Exclusive Coupons', max_length=255)),
                ('meta_description', models.TextField(default='Discover the best coupons, promo codes and deals from your favorite stores. Save money on your online shopping with CouponHub.')),
                ('meta_keywords', models.CharField(default='coupons, promo codes, deals, discounts, savings, coupon codes', max_length=255)),
                ('og_title', models.CharField(default='CouponHub - Save Money with Exclusive Coupons', max_length=255)),
                ('og_description', models.TextField(default='Discover the best coupons, promo codes and deals from your favorite stores. Save money on your online shopping with CouponHub.')),
                ('og_image', models.URLField(blank=True)),
                ('twitter_title', models.CharField(default='CouponHub - Save Money with Exclusive Coupons', max_length=255)),
                ('twitter_description', models.TextField(default='Discover the best coupons, promo codes and deals from your favorite stores. Save money on your online shopping with CouponHub.')),
                ('twitter_image', models.URLField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('no_index', models.BooleanField(default=False)),
                ('no_follow', models.BooleanField(default=False)),
                ('hero_title', models.CharField(default='Save Money with Exclusive Coupons', max_length=255)),
                ('hero_description', models.TextField(default='Discover the best deals and discounts from your favorite stores.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage SEO',
                'verbose_name_plural': 'Homepage SEO',
            },
        ),
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('home', 'Homepage'), ('coupon', 'Coupon'), ('store', 'Store'), ('category', 'Category'), ('page', 'Static Page')], max_length=20)),
                ('content_id', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.URLField(blank=True)),
                ('twitter_title', models.CharField(blank=True, max_length=255)),
                ('twitter_description', models.TextField(blank=True)),
                ('twitter_image', models.URLField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('no_index', models.BooleanField(default=False)),
                ('no_follow', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Metadata',
                'verbose_name_plural': 'SEO Metadata',
                'unique_together': {('content_type', 'content_id')},
            },
        ),
        migrations.AddField(
            model_name='category',
            name='seo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='coupons.seo'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='seo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon', to='coupons.seo'),
        ),
        migrations.AddField(
            model_name='store',
            name='seo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store', to='coupons.seo'),
        ),
    ]
