# Generated by Django 5.2.1 on 2025-08-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_homepageseo_seo_category_seo_coupon_seo_store_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageseo',
            name='og_image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='seo/og_images/'),
        ),
        migrations.AddField(
            model_name='homepageseo',
            name='twitter_image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='seo/twitter_images/'),
        ),
        migrations.AddField(
            model_name='seo',
            name='og_image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='seo/og_images/'),
        ),
        migrations.AddField(
            model_name='seo',
            name='twitter_image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='seo/twitter_images/'),
        ),
    ]
